{
 "title": "Circuits",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 }, "options": { "content": "# Next Race" } },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT year, date, name, location, country, url, lat, lng FROM public.\"RaceCircuits\"\r\nWHERE date > now()\r\nORDER BY date\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT year, date, name, location, country, url, lat, lng FROM public.\"RaceCircuits\"\r\nWHERE date > now()\r\nORDER BY date\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Land",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT year, date, name, location, country, url, lat, lng FROM public.\"RaceCircuits\"\r\nWHERE date > now()\r\nORDER BY date\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT year, date, name, location, country, url, lat, lng FROM public.\"RaceCircuits\"\r\nWHERE date > now()\r\nORDER BY date\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Nedtelling",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT year, date, name, location, country, url, lat, lng FROM public.\"RaceCircuits\"\r\nWHERE date > now()\r\nORDER BY date\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "All F1 Circuits",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 19, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT name, location, country, lat, lng FROM circuits LIMIT 300"
    },
    {
     "rawSql": "SELECT year, date, name, location, country, url, lat, lng FROM public.\"RaceCircuits\" WHERE year = '2023' LIMIT 300"
    },
    {
     "rawSql": "SELECT year, date, name, location, country, url, lat, lng FROM public.\"RaceCircuits\"\r\nWHERE date > now()\r\nORDER BY date\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Races 2023",
   "type": "table",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT year, round, date, name, location, country, alt, url FROM public.\"RaceCircuits\" WHERE year = '2023' LIMIT 300"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } }
 ]
}