{
 "title": "Constructors",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sesong",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Constructors",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  position as POS,\r\n  team,\r\n  wins,\r\n  points\r\nFROM public.\"ConstructorStandings\" \r\nWHERE raceid = (SELECT MAX(raceid) FROM public.\"ConstructorStandings\")\r\nGROUP BY position, team, points, wins\r\nORDER BY position ASC"
    }
   ]
  },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 } },
  { "title": "All time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Number of Teams through times",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  team,\r\n  nationality,\r\n  COUNT(DISTINCT raceid) AS num_races, \r\n  COUNT(DISTINCT year) AS num_years, \r\n  COUNT(points) AS num_points,\r\n  url\r\nFROM public.\"ConstructorResults\" \r\nGROUP BY team, nationality, url\r\nORDER BY num_points DESC"
    }
   ]
  },
  {
   "title": "Number of Nations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  nationality\r\nFROM public.\"ConstructorResults\" \r\nGROUP by nationality"
    }
   ]
  },
  {
   "title": "Construcor with most Years in F1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  team, \r\n  COUNT(DISTINCT year) AS num_years\r\nFROM public.\"ConstructorResults\" \r\nGROUP BY team, nationality, url\r\nORDER BY num_years DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Numbers of years",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  team, \r\n  COUNT(DISTINCT year) AS num_years\r\nFROM public.\"ConstructorResults\" \r\nGROUP BY team, nationality, url\r\nORDER BY num_years DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Constructors",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  team,\r\n  nationality,\r\n  COUNT(DISTINCT raceid) AS num_races, \r\n  COUNT(DISTINCT year) AS num_years, \r\n  COUNT(points) AS num_points,\r\n  url\r\nFROM public.\"ConstructorResults\" \r\nGROUP BY team, nationality, url\r\nORDER BY num_points DESC"
    }
   ]
  }
 ]
}