{
 "title": "Drivers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "2023 Seson", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Year",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT raceid, round, year\r\n\tFROM public.\"DriverResults\"\r\n\twhere raceid = (SELECT MAX(raceid) FROM public.\"DriverResults\")\r\n\tLIMIT 1;"
    }
   ]
  },
  {
   "title": "Round",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT raceid, round, year\r\n\tFROM public.\"DriverResults\"\r\n\twhere raceid = (SELECT MAX(raceid) FROM public.\"DriverResults\")\r\n\tLIMIT 1;"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT raceid, name\r\n\tFROM public.\"DriverStandings\"\r\n\twhere raceid = (SELECT MAX(raceid) FROM public.\"DriverStandings\")\r\n\tLIMIT 1;"
    }
   ]
  },
  {
   "title": "Driver Standings 2023",
   "type": "table",
   "gridPos": { "h": 22, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \"position\", name, points, wins\r\n\tFROM public.\"DriverStandings\"\r\n\tWHERE raceid = (SELECT MAX(raceid) FROM public.\"DriverStandings\")\r\n\tORDER BY \"position\" ASC;\r\n"
    }
   ]
  },
  {
   "title": "Last Race",
   "type": "table",
   "gridPos": { "h": 22, "w": 9, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT position, name, team, grid, laps, status, points\r\n\tFROM public.\"DriverResults\"\r\n\tWHERE raceid = (SELECT MAX(raceid) FROM public.\"DriverResults\")\r\n\tORDER BY \"position\" ASC;\r\n"
    }
   ]
  },
  {
   "title": "Points vs round",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT name, round, points\r\n\tFROM public.\"DriverStandings\"\r\n\twhere (year = 2023 and (position < 10))\r\n\tGROUP BY name, round, points\r\n\tORDER BY name DESC;"
    }
   ]
  },
  { "title": "Al Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Most wins",
   "type": "table",
   "gridPos": { "h": 22, "w": 5, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT name, COUNT(*) AS wins\r\nFROM public.\"DriverResults\"\r\nWHERE position = 1\r\nGROUP BY name\r\nORDER BY wins DESC;"
    }
   ]
  },
  {
   "title": "Most podiums",
   "type": "table",
   "gridPos": { "h": 22, "w": 5, "x": 5, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT name, COUNT(*) AS wins\r\nFROM public.\"DriverResults\"\r\nWHERE position IN (1,2,3)\r\nGROUP BY name\r\nORDER BY wins DESC;"
    }
   ]
  },
  {
   "title": "Points vs rounds 2021",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT name, round, points\r\n\tFROM public.\"DriverStandings\"\r\n\twhere (year = 2021 and (position < 10))\r\n\tGROUP BY name, round, points\r\n\tORDER BY name DESC;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 22, "w": 18, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  code,\r\n  name,\r\n  dob,\r\n  COUNT(DISTINCT raceid) AS num_races, \r\n  COUNT(DISTINCT year) AS num_years,\r\n  COUNT(CASE WHEN grid = 1 THEN 1 END) AS num_pole, \r\n  COUNT(CASE WHEN position = 1 THEN 1 END) AS num_wins,\r\n  COUNT(CASE WHEN grid = 1 AND position = 1 THEN 1 END) AS num_pole_wins,\r\n  COUNT(CASE WHEN position IN (1,2,3) THEN 1 END) AS num_podiums, \r\n  COUNT(DISTINCT team) AS num_teams,\r\n  url\r\nFROM public.\"DriverResults\" \r\nGROUP BY name, code, dob, url\r\nORDER BY dob DESC"
    }
   ]
  }
 ]
}